---
- hosts: all
  gather_facts: false

  tasks:
    - name: create example charge_back_request
      brightcomputing.bcm.charge_back_request:
        name: example
        groupByUser: true
        startTime: now/y
        endTime: now/y
