---
- hosts: all
  vars_files:
    - /root/.road-runner/install_config.yaml

  tasks:   
 
    - name: add tracker {{ tracker_name }} to HPC engine {{ engine_name }}
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/add-ScaleHpcQueueTracker.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/tmp/autoscaler-{{ index }}.yaml"
        mode: "0644"