---
- hosts: all
  vars_files:
    - /root/.road-runner/install_config.yaml

  tasks:   
 
    - name: "write a playbook that adds the {{ role_name }} role to the {{ overlay_name }} configuration overlay"
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/add-role-to-slurm-client-overlay.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/tmp/wlm-{{ index }}.yaml"
        mode: "0644"