---
- hosts: all
  gather_facts: true
  vars_files:
    - /root/.road-runner/install_config.yaml
    
  tasks:
  
    # write the user password to a secure file
    - name: write the user password to a secure file
      copy:
        dest: /root/.userpassword
        content: "{{ password }}"
        mode: "0600"
