---
- hosts: all
  vars_files:
    - /root/.road-runner/install_config.yaml

  tasks:   
 
    - name: add HPC engine {{ engine_name }} to {{ role_name }} role
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/add-resource.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/tmp/wlm-{{ index }}.yaml"
        mode: "0644"