---
- hosts: localhost
  gather_facts: true
  
  tasks:
    - name: list all software images
      brightcomputing.bcm92.software_image_info: {}
      register: result
      
    - name: Get list of modules from existing Bright software images
      set_fact:
        images_need_modules: "{{ result.software_images }}"
        
    - name: Write playbook {{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yml
      ansible.builtin.blockinfile:
        insertafter: EOF
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yml" 
        block: "{{ lookup('template', 'templates/append-kernel-modules.j2') }}"
        marker: ""
        
    # - name: show variables
      # debug:
        # msg: "{{ images_need_modules[0]['modules'] }}"
