---
- hosts: all
  gather_facts: true
 
  tasks:
      
    - name: Touch {{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml
      ansible.builtin.file:
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml"
        state: touch
      
    - name: Write playbook {{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml
      ansible.builtin.blockinfile:
        insertafter: EOF
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml" 
        block: "{{ lookup('template', 'templates/clone-software-images.j2') }}"
        marker: ""
      loop: "{{ ansible_local['custom']['software_images'] }}"
