---
- hosts: all
  gather_facts: true
 
  tasks:
      
    - name: Touch {{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml
      ansible.builtin.file:
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml"
        state: touch
      
    - name: Write playbook {{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml
      ansible.builtin.blockinfile:
        insertafter: EOF
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml" 
        block: "{{ lookup('template', 'templates/clone-software-images.j2') }}"
        marker: ""
      loop: "{{ ansible_local['custom']['software_images'] }}"
      
    - name: list all software images
      brightcomputing.bcm92.software_image_info: {}
      register: result
      
    - name: Get list of modules from existing Bright software images
      set_fact:
        images_need_modules: "{{ result.software_images }}"
    
    # - name: "write playbook that creates the {{ image_name }} software image by cloning the {{ clone_from }} software image"
      # ansible.builtin.template:
        # src: "{{ ansible_local['custom']['install_dir'] }}/templates/append-kernel-modules.j2"
        # dest: "{{ ansible_local['custom']['install_dir'] }}/roles/software_images/tmp/software-image-1.yaml"
        # mode: "0644"
        
    - name: Write playbook {{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml
      ansible.builtin.blockinfile:
        insertafter: EOF
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/software_images/tasks/main.yaml" 
        block: "{{ lookup('template', 'templates/append-kernel-modules.j2') }}"
        marker: ""
