---
- hosts: all
  gather_facts: true
  vars_files:
    - /root/.road-runner/install_config.yaml
    
  tasks:
        
    - name: "Writing playbook that configures NIC {{ device_name }} of node {{ node_name }}"
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/configure-node-nic.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/tmp/nodes-{{ index }}.yaml"
        mode: "0644"