---
- hosts: all
  gather_facts: true
  vars_files:
    - /root/.road-runner/install_config.yaml
    
  tasks:
        
    - name: "Cloning {{ clone_from }} -> {{ node_name }}"
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/create-node.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/roles/nodes/tmp/nodes-{{ index }}.yaml"
        mode: "0644"