---
- hosts: all
  gather_facts: true
  vars_files:
    - /root/.road-runner/install_config.yaml
    
  tasks:
        
    - name: "writing playbook that creates the {{ category_name }} category"
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/create-category.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/tmp/categories-{{ index }}.yaml"
        mode: "0644"