---
- hosts: all
  gather_facts: true
 
  tasks:
      
    - name: Touch {{ ansible_local['custom']['install_dir'] }}/roles/license/tasks/main.yml
      ansible.builtin.file:
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/license/tasks/main.yml"
        state: touch
      
    - name: Write playbook {{ ansible_local['custom']['install_dir'] }}/roles/license/tasks/main.yml
      ansible.builtin.blockinfile:
        insertafter: EOF
        path: "{{ ansible_local['custom']['install_dir'] }}/roles/license/tasks/main.yml" 
        block: "{{ lookup('template', 'templates/install-license.j2') }}"
        marker: ""
        
    - name: Ensure SELinux is set to enforcing mode
      ansible.builtin.lineinfile:
        path: /cm/local/apps/cmd/etc/cmd.conf
        regexp: '^# AdvancedConfig'
        line: 'AdvancedConfig = { "DeviceResolveAnyMAC=1" }'
