---
- hosts: all
  gather_facts: true
  vars_files:
    - /root/.road-runner/install_config.yaml
  
  tasks:
        
    - name: create cm-jupyter-setup configuration file
      template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/cm-jupyter-setup.conf.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/cm-jupyter-setup.conf"
        mode: "0644"
 
    - name: create the install-jupyter.yaml playbook
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/install-jupyter.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/roles/jupyter/tasks/main.yaml"
        mode: "0644"