---
- hosts: all
  gather_facts: true
  vars_files:
    - /root/.road-runner/install_config.yaml
    
  tasks:
        
    - name: patch cuda driver service file
      ansible.builtin.template:
        src: "{{ ansible_local['custom']['install_dir'] }}/templates/patch-cuda-driver-service-file.j2"
        dest: "{{ ansible_local['custom']['install_dir'] }}/tmp/packages-{{ index }}.yaml"
        mode: "0644"