---
- hosts: node01
  roles:
    #- apt_upgrade_node

- hosts: localhost
  roles:
    - networks
    #- software_images
    #- categories
    #- nodes
    #- packages
    #- kubernetes
    #- wlms
    #- autoscaler
    #- csps
    #- jupyter
    #- users
    #- apps
    