---
- hosts: node01
  roles:
    #- updates

- hosts: localhost
  roles:
    #- license
    # - networks
    # - software_images
    # - categories
    # - nodes
    #- packages
    #- kubernetes
    #- wlms
    #- autoscaler
    #- csps
    #- jupyter
    #- users
    - power
    #- apps
    