---
- hosts: localhost
  roles:
    - software_images
    #- categories
    #- nodes
    #- packages
    #- kubernetes
    #- wlms
    #- autoscaler
    #- csps
    #- jupyter
    #- users
    #- apps
    
- hosts: node01
  roles:
    - apt_update_node
