---
- hosts: node01
  roles:
    #- updates

- hosts: localhost
  roles:
    - license
    #- networks
    #- software_images
    #- updates
    #- categories
    #- nodes
    #- packages
    #- kubernetes
    #- wlms
    #- autoscaler
    #- csps
    #- jupyter
    #- users
    #- apps
    